name: Deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Enable bundler cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          npm install -g @mermaid-js/mermaid-cli

      - name: Setup deploy options
        id: setup
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ ${GITHUB_REF} == refs/pull/*/merge ]]; then
            echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
            echo "NO_PUSH=--no-push" >> $GITHUB_ENV
          elif [[ ${GITHUB_REF} == refs/heads/* ]]; then
            echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi
          echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_ENV

      - name: Deploy website
        run: |
          yes | bin/deploy --verbose ${NO_PUSH:-} \
            --src ${SRC_BRANCH:-master} \
            --deploy ${DEPLOY_BRANCH}
